### ISSUE TITLE
[Testbirds Feedback] Others

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app#100]
- Connect the app to Google Maps
- Change the event section, e.g. by making it possible to minimize,  create an own icon for events or have it as the starting page
- Don’t use block layout of the text
- Insert a button that would take you to the main menu instantly
- "What language do you speak?" could be written in other languages as well, just to make sure it is understood

**Comment by Dalanie** [comment]
Vielleicht sollten wir die Auflistung aufsplitten

**Comment by Meash** [comment]
Jep, fände ich auch besser
