### ISSUE TITLE
Minimum Android Version Req'd

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/app#115]
Hey,

was ist die niedrigste Android Version die die App bisher braucht?
Was sind die konkreten Features die das beschränken?

Vorschlag: 
1. Identifizieren der 'Limiters'
2. Prüfen, wie weit die Version nach unten gedrückt werden kann.

Rationale:
Flüchtliche haben zwar smartphones, aber teils alte, gebrauchte, von Billigherstellern. Es wird wohl keine derartige Statistik geben, aber ich könnte wetten, viele haben nur Android 2.x. Es wäre schade, wenn diese ausgeschlossen würden.

**Comment by Dalanie** [comment]
Alles bis 2.3 wird unterstützt 😊, und an der Version hängt so ziemlich
jede library
