### ISSUE TITLE
gradle

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/app#116]
nutzt ihr gradle? Android studio bettelt mich quasi an, auf gradle zu migrieren.
Ist das gewollt von allen? Soll das ins repo oder wenn dann jeder bei sich? Wird ja glaube auch von anderen IDEs unterstützt.

**Comment by ammyg** [comment]
Ja, wir nutzen gradle und es sind auch alle benötigten Dateien im Repo
vorhanden. Beim Öffnen in Android Studio darfst du nur nicht den
root-Ordner nehmen, sondern app/android. Ansonsten erkennt Android Studio
oder IntelliJ das gradle-Projekt nicht richtig.

Lemming0815 <notifications@github.com> schrieb am Sa., 21. Nov. 2015 11:09:

**Comment by Dalanie** [comment]
Jep, Gradle ist status-quo in der Android Entwicklung. Deutlich lesbarer als Maven oder Ant und dennoch kompatibel mit Maven Repos. Wie @ammyg bereits gesagt hat, befindet sich alles wichtige bereits im Repo
