### ISSUE TITLE
Anzeige von Gliederungspunkt "Feedback, Kontakt und mögliches Engagement"

### ISSUE THREAD

**Issue by julia-goetz** [Integreat/app#117]
Der letzte Punkt, der Infos über die Macher der App etc. enthält, sollte anstatt als eigener Gliederungspunkt mit, beispielsweise, einem kleinen ( i ) Zeichen, About Us oder so irgendwo angezeigt und angewählt werden können.

**Comment by Dalanie** [comment]
@Meash Wie loesen wir das?`Hardgecoded in der Android-App? Oder eventuell extra Type 'Impressum' wo wir derzeit Event/Page haben?

**Comment by Meash** [comment]
Eigenen Typ finde ich gut, vielleicht kann man das so bauen, dass sich die
App das unabhängig vom Ort zieht, sondern aus der root site (
vmkrcmar21.informatik.tu-muenchen.de/wordpress).
@julia-goetz die Inhalte sind gleich für jede Instanz und werden nur von
uns verwaltet oder?

**Comment by Dalanie** [comment]
Kann man einbauen, ja!

**Comment by julia-goetz** [comment]
Si. Wie @Dalanie sagt ist das quasi das Impressum, mit etwas Zusatztext. Betrifft denke ich auch langfristig nur uns, die Kommunen können sich, falls gewünscht, dafür ja eine Page einrichten

**Comment by Dalanie** [comment]
Also ist das Serverseitig zu lösen unnötig? Wenn es nur uns betrifft mach
ich es hardcoded

**Comment by julia-goetz** [comment]
Ist recht so!

**Comment by Meash** [comment]
Finde, wir sollten in der Lage sein, das ändern zu können
Am 21.11.2015 22:36 schrieb "Daniel Langerenken" <notifications@github.com>:

> Also ist das Serverseitig zu lösen unnötig? Wenn es nur uns betrifft mach
> ich es hardcoded
>

**Comment by julia-goetz** [comment]
doch nicht recht so :-)

**Comment by dkehne** [comment]
Der Punkt hier bezieht sich auf das stadtspezifische Impressum - Julia Hüther ist da erste Ansprechpartnerin für die Augsburg Instanz z.B.

**Comment by Meash** [comment]
Heißt Impressum soll Stadt spezifisch anpassbar sein aber trotzdem
gesondert behandelt werden?
Am 21.11.2015 23:25 schrieb "Daniel Kehne" <notifications@github.com>:

**Comment by dkehne** [comment]
Ja also wäre cool wenn es im Menü als Punkt auftaucht, aber trotzdem auf CMS Content verweist. Geht das?

**Comment by Meash** [comment]
Die Frage ist, ob es Instanz spezifisch einstellbar sein soll oder nicht.
Was du mit dem Menü meinst, habe ich nicht verstanden.

**Comment by Dalanie** [comment]
er meint die navigation, ja das geht.

**Comment by Meash** [comment]
@dkehne Wie sieht's mit der Instanz spezifischen Einstellbarkeit aus?

**Comment by dkehne** [comment]
Also in jeder Stadt gibt es ein anderes Impressum. Das meinte ich damit.

**Comment by Meash** [comment]
Okay also markieren wir es doch nicht als solches und lassen alles wie
gehabt?

**Comment by Dalanie** [comment]
Weiss nicht wieviel Aufwand es fuer euch ist, aber wenn ihr nen Flag "Impressum" habt, koennen wir das in der App definitiv anders anzeigen. Nur muesstet ihr dieses Flag halt haben und am Besten nur einmal setzen :)

**Comment by Meash** [comment]
Ja muss man erst bauen, das würde dann ein gesonderter Menü Punkt.

**Comment by Meash** [comment]
Live auf CMS Seite, abrufbar unter http://vmkrcmar21.informatik.tu-muenchen.de/wordpress/augsburg/de/wp-json/extensions/v0/modified_content/disclaimer?since=2000-12-31T16%3A00%3A00-0800

**Comment by Dalanie** [comment]
bissl aufwändiger afaik, schau ich mir an, wenn ich mehr zeit hab

**Comment by Meash** [comment]
Ist recht wichtig, da dort auch das rechtliche Zeug drinsteht. Also wer ist verantwortlich für den Inhalt.
In den Seiten wird das nicht mehr angezeigt, da es ja im Impressum steht.
