### ISSUE TITLE
Buttons zu klein 

### ISSUE THREAD

**Issue by Meash** [Integreat/app#118]
Gerade Feedback bekommen: 

* Tab Buttons unten zu klein, man kommt leicht aus versehen auf den zurück Knopf -> Größer und nach oben 
* Ort ändern und Einstellungen ähnlich, vgl Gmail, die haben da auch mehr Abstand. Sollten imo trotzdem die Struktur nicht verdecken, vlt Einstellungen Knopf iwo und da auch Ort ändern

**Comment by Dalanie** [comment]
Warum klickt man? Sollte doch swipebar sein. Nach oben sieht nicht sehr
schön aus.. Hatte das vorher bereits drin

**Comment by Meash** [comment]
Weil nicht jeder IT affin ist und checkt dass man swypen kann :D
Am 21.11.2015 23:10 schrieb "Daniel Langerenken" <notifications@github.com>:

**Comment by visi0nary** [comment]
>Warum klickt man? Sollte doch swipebar sein. Nach oben sieht nicht sehr schön aus.. Hatte das vorher bereits drin

Jo, zumal das ja bei Android quasi Richtlinie ist. Nichtsdestotrotz habe ich als Neuling lange gebraucht, um den Veranstaltungstab überhaupt wahrzunehmen. Ein Tutorial für den ersten Start wäre also gut, das halt kurz die beiden Tabs erklärt und hervorhebt. Was meint ihr?

Die Settingsbuttons sind echt winzig, da stimme ich zu. Ich teste mal ein wenig rum

**Comment by Dalanie** [comment]
https://github.com/Integreat/app/issues/128

**Comment by visi0nary** [comment]
Optimalerweise sollten die Tabs aber dann doch oben sein und beim Scrollen verschwinden - das folgt dann auch den offiziellen Designrichtlinien ;) Kann mich mal jemand per Mail kontaktieren wegen den Mockup, die die Designer zusammengezimmert haben?

**Comment by Dalanie** [comment]
Naja, streng genommen sollte die Actionbar verschwinden und die tabs an
dessen stelle rücken. Könnten wir einbauen. Ich bin jedoch vom Design nicht
wirklich überzeugt
😉

**Comment by visi0nary** [comment]
Jain. Im Play Store verschwindet z.B. auch beides, was ja auch sinnvolle ist, um den Content darzustellen. Ich teste mal rum ;)

**Comment by julia-goetz** [comment]
Mail bzgl. Design kommt!

**Comment by Dalanie** [comment]
Klingt gut! Bitte Änderungen, sofern abgeschlossen, zuerst auf nen Branch pushen, damit wir Design-technisch mit allen drübergehen können ;)
