### ISSUE TITLE
Navigation bar scroll behaviour

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/app#120]
Die sidebar lässt sich nur scrollen, wenn man perfekt vertikal wischt. leichte diagonale Abweichung in der Wischrichtung schließt die sidebar. Ist das Verhalten von der standard library übernommen?

Solution: auch diagonale wischrichtung als vertikale Geste intepretieren. Der breakpoint könnte bei 45° liegen. Alles darüber würde dann als horizontale Geste interpretiert.

**Comment by Dalanie** [comment]
Alle Gesten sind Standardverhalten in Android - In der Navigation kann ich aber auch diagonal swipen und er scrollt dennoch. Was für ein Gerät nutzt du?

**Comment by Lemming0815** [comment]
Ein Motorola xt890 mit cm11. 
Habe aber in keinen anderen apps dieses Problem. 
Aber schon mal interessant dass es bei dir geht. 
On 25 Nov 2015 15:46, Daniel Langerenken <notifications@github.com> wrote:Alle Gesten sind Standardverhalten in Android - In der Navigation kann ich aber auch diagonal swipen und er scrollt dennoch. Was für ein Gerät nutzt du?

**Comment by Dalanie** [comment]
Sorry, ich nutze Standard-Libs, nicht reproduzierbar
