### ISSUE TITLE
Cloning to IntelliJ doesn't work out of the box

### ISSUE THREAD

**Issue by visi0nary** [Integreat/app#124]
The file structure is a bit weird because we have a **app/android/app** folder but it should be **app/app** to be fully compatible to IntelliJ out of the box. This would possibly attract more developers because nobody likes to fix his project setup before contributing ;)

**Comment by Dalanie** [comment]
I thought by now every person switched to Android Studio - anyways. Are you sure about this? I can't remember creating the project, but I am almost sure that I did it the default way.

**Comment by visi0nary** [comment]
Yep, I was talking about Android Studio implicitly. It complains that no gradle files are found which is due to the file structure I guess

**Comment by Dalanie** [comment]
I checked out the project in a new directory and had no problems importing it into android studio. I selected the top directory as "project".

Don't know whether or not we should change something with the project structure... I'm fine with any changes if you think, this attracts more developers ;)
