### ISSUE TITLE
No proper checking if network connection is available

### ISSUE THREAD

**Issue by visi0nary** [Integreat/app#125]
If I start the app without network connections (e.g. flight mode) the screen says that no entries were found. If I go online again the contents are not refreshed and there's also no way to manually do it.

**Comment by ammyg** [comment]
Da sind wir von einem Issue des SuperRecyclerView betroffen :-1: 
https://github.com/Malinskiy/SuperRecyclerView/issues/66

**Comment by Dalanie** [comment]
Jep.. Genau wie das Icon zum refreshen bei leerer Liste hinter dem Bild landet... 

Eventuell umsteigen auf ultimate recyler?

**Comment by Dalanie** [comment]
Ähm, nochmal angeschaut. Man kann durchaus swipen und dadurch die Liste aktualisieren. Leider ist das swipe-symbol jedoch hinter dem eigentlichen screen.

**Comment by Dalanie** [comment]
ich tausche gerade die library aus
