### ISSUE TITLE
Mark automatic translations

### ISSUE THREAD

**Issue by Meash** [Integreat/app#134]
In Integreat/cms#226 we remote the disclaimer at the beginning of the automatically translated texts ("This text was translated automatically.."). Then plan is to reflect the same information with a flag `"automatic_translation": true` instead.
We should then mark this information in the app again, e.g. by re-introducing the disclaimer at the top of the text again (but not in the overview).

**Comment by Dalanie** [comment]
Is this implemented yet?

**Comment by Dalanie** [comment]
Finished implementing on client-side. A snackbar (which you can dismiss) is shown when the page is auto translated.
