### ISSUE TITLE
Suchstring soll EasterEgg auslösen

### ISSUE THREAD

**Issue by dkehne** [Integreat/app#135]
es gibt ein flag im CMS was mitgeliefert wird über die REST API, ob die instanz BETA (0/1, Default=1) ist. In der Stadtauswahl werden nur städte angezeigt, die auf BETA = 0 stehen.

dann machen wir das folgende und zwar, wird beim triggern der searchfunktion also Enter eine if-abzweigung aufgerufen, die das folgende abfragt:

IF SEARCH_TERM != "Wirschaffendas" { ausführung der normalen search logik } ELSE (Alle Städte anzeigen, die auf BETA 1 oder 0 stehen.

**Comment by Dalanie** [comment]
Lustig dass du 0 als an interpretierst
😁

**Comment by Dalanie** [comment]
Memo an mich selbst: Column 'BETA' hinzufuegen und via ALTER TABLE ADD COLUMN handeln. Andernfalls werden Daten geloescht
