### ISSUE TITLE
Tabellengröße anpassen (kein Overflow)

### ISSUE THREAD

**Issue by dkehne** [Integreat/app#16]
...oder andere Lösung um das folgende Problem zu beheben. Man kann zwar durch die Tabelle Scrollen aber sieht im ersten Moment ungewollt und Buggy aus.
![quer_hoch](https://cloud.githubusercontent.com/assets/4182469/10275385/4513e956-6b47-11e5-85f4-031da528b479.jpg)

**Comment by matsair** [comment]
So sieht übrigens die Tabelle in **Lebensmittel und Kleidung** in der App mit JS aus:

![screenshot_20151120-213239](https://cloud.githubusercontent.com/assets/5218859/11311163/691c81f4-8fce-11e5-8ed4-3b5440ef4425.png)

**Comment by Dalanie** [comment]
schaut gut aus! however, kann man iwie rauskriegen, ob es ueberhaupt nen linewrap gibt? die tabelle soll nur als liste dargestellt werden wenn diese zu gross fuer die darstellung ist.

irgendwie scheint css nicht wirklich zuverlaessig zu sein

**Comment by Dalanie** [comment]
Ich habe es implementiert - apk befindet sich im Drive. Lädt nichts aus dem netz.

Wie auch immer... ich bin nicht von der Lösung überzeugt.. finde die generierten Listen nicht sehr schön..

**Comment by Dalanie** [comment]
https://jsfiddle.net/7o6cv3oj/ ich hab mal nen jsfiddle aufgesetzt. Da seht ihr das an nem Beispiel. Feel free to edit Javasript/HTML (wobei der Teil im div content unverändert bleiben sollte)

**Comment by Meash** [comment]
Ansatz mit Border: https://jsfiddle.net/7o6cv3oj/4/
Die Inhalte sind bei dem Beispiel leider auch nicht die schönsten, weil einige Zellen fehlen.

**Comment by Dalanie** [comment]
http://wpdatatables.com/ @Meash  ?

**Comment by Dalanie** [comment]
implemented... liegt am backend wie ihr das dann gestaltet

**Comment by Meash** [comment]
@Dalanie du meinst, wir sollen das Plugin nehmen statt der normalen Tabellen? Speichern die das in einem anderen Format ab?
