### ISSUE TITLE
Keine Ladeanzeige beim Aktualisieren 

### ISSUE THREAD

**Issue by Meash** [Integreat/app#74]
Derzeit muss man (u.U. ziemlich lange) warten, bis die neuen Daten geladen sind.
Stattdessen keine Ladeanzeige zeigen und im Hintergrund aktualisieren. 
Beim Wechsel auf eine noch nicht geladene Sprache soll die Ladeanzeige bestehen bleiben.

**Comment by Dalanie** [comment]
sollte behoben sein
