### ISSUE TITLE
Stadtauswahl-Screen vereinfachen

### ISSUE THREAD

**Issue by MaximilianSchreieck** [Integreat/app#76]
Bisheriges Feedback zum Stadtauswahl-Sreen:
- Zur Ansprache von Kommunen gut geeignet, Flüchtlinge können dagegen wohl wenig mit Stadtlogos anfangen.
- Vorschlag: Entweder Map-basierte Anzeige der Städte oder Kacheln mit "blurry" Foto des Stadtwahrzeichens und darauf der Stadtname

**Comment by Dalanie** [comment]
hey @ammyg - der erste Kommentar, wäre da vielleicht folgende Library was: https://github.com/amlcurran/ShowcaseView ?

**Comment by ammyg** [comment]
Hm... Das ist ja irgendwie mehr dazu geeignet um spezielle (evtl. schwer zu findende) Funktionen in der App dem Nutzer zu zeigen. Sowas haben wir bei uns ja eigentlich gar nicht.
Mein Ansatz sollte dem Nutzer beim ersten Start eher zeigen, was unsere App eigentlich grob kann, so im Stil wie es Google bei seinen Apps auch oft macht (Siehe z. B. Docs).
Frage in die Runde: Brauchen wir so etwas? Evtl. ist mein Ansatz auch etw. zu spielerisch ;).

@Dalanie kannst du mal eine signierte apk erstellen, damit das mal die Runde kurz testen kann :).

**Comment by Dalanie** [comment]
Hey!
Ich hatte jetzt erst Zeit gefunden reinzuschauen.

Erster Eindruck: Super Design! Gefällt mir sehr!
Vor allem die Stadtauswahl - das würde ich gerne auch so für die Sprache implementieren!

Das einzige Problem was ich mit den Introduction-Feldern sehe: Die Sprache ist zu dem Zeitpunkt noch nicht bekannt und vielleicht verstehen die Nutzer nicht, was das ganze dann bedeutet.

Wie wäre es mit der Reihenfolge: WELCOME - STADT - SPRACHE - INTRO - Mainpage ?

**Comment by Dalanie** [comment]
Die APK befindet sich im Drive "app_start_redesign".

Ich habe einen Nullpointer bei Location behoben (bzw. nur durch nen if-else ersetzt). Kannst du mal schauen ob das Verhalten sich dadurch ändert?

**Comment by ammyg** [comment]
Danke fürs Erstellen der apk.
So wie ich das gesehen habe, müsste das Verhalten gleich geblieben sein :).

**Comment by Dalanie** [comment]
Hey,
ich hab angelehnt an deinem Feature-Branch den Stadtauswahl-Screen angepasst. Sprache auch, aber das gefällt mir noch nicht ganz so ;)
