### ISSUE TITLE
Gleiches Farbschema für alle Städte

### ISSUE THREAD

**Issue by MaximilianSchreieck** [Integreat/app#79]
Vorschlag vom Grafiker: Keine verschiedenen Farben pro Stadt, da unruhig und kein Wiedererkennungseffekt.
Stattdessen einheitliches Farbschema abgestimmt mit Logo/Corporate Design.

**Comment by Dalanie** [comment]
Betrachtet man aktuelle Android 5.X/6.X Apps, so sieht man, dass vor allem innerhalb einer App viel mit den Farben "gespielt" wird. Da man normalerweise nicht zwischen den Städten wechselt, ändert sich die Farbe des Designs auch nicht und es ist nicht unruhig. Zu Beginn nehmen wir die Logo-Farben und nach dem Setup die Stadtfarben. Ich schließe es erstmal und nachdem das Design-Team drübergeschaut hat, öffne ich es u.U. wieder
