### ISSUE TITLE
Klick auf den navigation header?

### ISSUE THREAD

**Issue by matsair** [Integreat/app#84]
Was sollte da passieren? Zur zeit werden alle Pages einfach gelistet?
Vielleicht könnte man hier zur Stadtauswahl kommen?

**Comment by Dalanie** [comment]
Wie würde man sonst wieder zu allen Seiten zurückkommen? (Außer zurück zu klicken was jetzt möglich ist)

**Comment by matsair** [comment]
Ich finds auch gut, dass man zu allen seiten kommt. dieser punkt kam aus unserem treffen in münchen hervor, aber hatte wohl keine genauen hintergründe. ich close das erstmal.
