### ISSUE TITLE
Bei zurück Liste der Seiten aufklappen 

### ISSUE THREAD

**Issue by Meash** [Integreat/app#92]
Wenn ich in der Grundansicht bin und zurück drücke, erwarte ich wieder die Liste an Seiten links. Stattdessen kommt die Frage zum schließen.

Beispiel: ich klappe die Seiten Übersicht auf, öffne eine Seite und gehe zweimal zurück.

**Comment by Dalanie** [comment]
Okay - dann brauchen wir aber auch ne "Visualisierung" dass es zuruck gehen kann. Normalerweise wird das NavDrawerIcon zu einem Pfeil - aber dann weiss man vielleicht nicht, dass es den NavDrawer noch gibt... Ich ueberleg mir was

**Comment by Dalanie** [comment]
Nevermind, ich versteh nicht ganz, was ihr damit bezwecken wollt (es gab schon nen ähnliches Ticket).

Das ist weder im StyleGuide von Android noch halte ich es für sinnvoll. Wie beendet man dann eine Anwendung? Menu Button klicken ist keine Alternative für mich.

Was jetzt passiert ist: Selektierst du eine Seite mit Subpages, und drückst zurück, siehst du wieder alle pages

**Comment by Meash** [comment]
Wenn man wieder zurück zu allen Seiten kommt und danach mit einem zurück
die Anwendung schließen kann, finde ich es gut.
