### ISSUE TITLE
Impressum/Contact/Help/Questions Fragment

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app#93]
Fragment (vllt als DialogFragment) implementieren, um Impressum/Contact/Help anzuzeigen. 

Textvorschlaege? @dkehne ?

**Comment by dkehne** [comment]
was ist mit dem aktuellen Feedback/Kontakt Text aus dem Guide? 

Die Macher dieses Leitfadens freuen sich über Ihre Anregung und Kritik, aber natürlich auch über Lob. Auch Ihre Fragen beantworten wir natürlich gerne.  Falls Sie weitere Angebote für Asylbewerber haben oder auch mit Ihrem Unternehmen in diesem Guide erscheinen möchten, wenden Sie sich bitte mit Ihrem Anliegen an daniel.kehne@web.de

Haftungshinweis:
Die hier aufgeführten Inhalte wurden mit der größtmöglichen Sorgfalt erstellt und aufbereitet. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann jedoch keine Gewähr übernommen werden. Der Betreiber haftet daher nicht für Schäden oder Folgen, die im Zusammenhang mit der Verwendung dieser Inhalte stehen, sofern kein vorsätzliches oder grob fahrlässiges Verhalten nachzuweisen ist.

Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.

**Comment by dkehne** [comment]
Okay ergänzend muss noch

Icons provided by www.flaticon.com

**Comment by Lemming0815** [comment]
gibts ne englische Übersetzung davon?
Soll ich mich mal dran versuchen?

**Comment by dkehne** [comment]
Ja der aufgeführte Text ist in englisch, arabisch, persisch und französisch bereits im System.

**Comment by dkehne** [comment]
Läuft.
